---

- hosts: all
  roles:
    - role: ansible-role-ssl-certificate

  handlers:
    - name: Create file when ssl certificate changed
      listen: ssl certificate changed
      # Use command so that we get an error if the handler is triggered during
      # the idempotence check
      command: touch /tmp/ssl-certificate-changed
